/**
* @author long.qian
 */

package auth_rbac

// =================================================================================
// Code generated by LazyFrame Gen tool. DO NOT EDIT.
// If you want to develop the code, write the file [ gen_model_rbac_log.go]  in the same directory.
// =================================================================================

import (
	"gorm.io/gorm"
)

// RbacLog Auth-操作记录日志
type RbacLog struct {
	gorm.Model
	Body      string `json:"body" gorm:"type:TEXT;comment:请求Body体参数"`                 // 请求Body体参数
	Ip        string `json:"ip" gorm:"size:100;not null;comment:IP地址"`                // IP地址
	Url       string `json:"url" gorm:"size:500;not null;comment:访问地址"`               // 访问地址
	UrlParams string `json:"url_params" gorm:"size:1000;not null;comment:地址参数"`       // 地址参数
	LoginName string `json:"login_name" gorm:"size:100;not null;comment:登陆用户"`        // 登陆用户
	Status    int64  `json:"status" gorm:"not null;default:0;comment:状态 0：正常 1：鉴权失败"` // 状态 0：正常 1：鉴权失败
}

func (RbacLog) TableName() string {
	return "rbac_log"
}
