/**
* @author long.qian
*/

package auth_rbac

// =================================================================================
// Code generated by LazyFrame Gen tool. DO NOT EDIT.
// If you want to develop the code, write the file [ gen_dto_rbac_permissions.go]  in the same directory.
// =================================================================================

import (
	"go-lazy-frame/pkg/pub/query"
)

// RbacPermissionsCreateDto RbacPermissions 创建请求 DTO
type RbacPermissionsCreateDto struct {
	// 权限描述
    Description string `json:"description" binding:"required"`
	// 权限值
    Permission string `json:"permission" binding:"required"`
}

// TransformTo 从 RbacPermissionsCreateDto 转换为 实体
func (me RbacPermissionsCreateDto) TransformTo() *RbacPermissions {
	model := &RbacPermissions{
		Description: me.Description,
		Permission: me.Permission,
	}
	return model
}

// RbacPermissionsQueryDto 查询请求 DTO
type RbacPermissionsQueryDto struct {
	// 【id】Id 全匹配
	Id interface{} `json:"id" field:"id"  type:"equal"`
	// 【id】Id in 查询
	IdIn []interface{} `json:"idIn" field:"id"  type:"in"`
	// 【id】Id 范围（包含边界）
	IdBetween []interface{} `json:"idBetween" field:"id"  type:"between"`
	// 【id】Id 大于
	IdGt interface{} `json:"idGt" field:"id"  type:"gt"`
	// 【id】Id 大于等于
	IdGte interface{} `json:"idGte" field:"id"  type:"gte"`
	// 【id】Id 小于
	IdLt interface{} `json:"idLt" field:"id"  type:"lt"`
	// 【id】Id 小于等于
	IdLte interface{} `json:"idLte" field:"id"  type:"lte"`
	// 【created_at】CreatedAt 时间范围（包含边界）
	CreatedAtBetween []interface{} `json:"createdAtBetween" field:"created_at" type:"between"`
	// 【updated_at】UpdatedAt 时间范围（包含边界）
	UpdatedAtBetween []interface{} `json:"updatedAtBetween" field:"updated_at" type:"between"`
	// 【description】权限描述 全匹配
	Description interface{} `json:"description" field:"description"  type:"equal"`
	// 【description】权限描述 in 查询
	DescriptionIn []interface{} `json:"descriptionIn" field:"description"  type:"in"`
	// 【description】权限描述 左匹配(xxx%)
	DescriptionLeft interface{} `json:"descriptionLeft" field:"description"  type:"likeRight"`
	// 【description】权限描述 右匹配(%xxx，查询有性能影响)
	DescriptionRight interface{} `json:"descriptionRight" field:"description"  type:"likeLeft"`
	// 【description】权限描述 模糊匹配(%xxx%，查询有性能影响)
	DescriptionMiddle interface{} `json:"descriptionMiddle" field:"description"  type:"likeMiddle"`
	// 【permission】权限值 全匹配
	Permission interface{} `json:"permission" field:"permission"  type:"equal"`
	// 【permission】权限值 in 查询
	PermissionIn []interface{} `json:"permissionIn" field:"permission"  type:"in"`
	// 【permission】权限值 左匹配(xxx%)
	PermissionLeft interface{} `json:"permissionLeft" field:"permission"  type:"likeRight"`
	// 【permission】权限值 右匹配(%xxx，查询有性能影响)
	PermissionRight interface{} `json:"permissionRight" field:"permission"  type:"likeLeft"`
	// 【permission】权限值 模糊匹配(%xxx%，查询有性能影响)
	PermissionMiddle interface{} `json:"permissionMiddle" field:"permission"  type:"likeMiddle"`
	// 排序，例如：["id desc", "name asc"] 字段名为每个字段说明后的开头中【】内的内容，方式只能为 desc 或 asc。支持指定多个字段排序
	OrderBy []string `json:"orderBy"`
}

// RbacPermissionsUpdateDto 更新请求 DTO
type RbacPermissionsUpdateDto struct {
	// Id
    Id interface{} `json:"id"`
	// 权限描述
    Description interface{} `json:"description"`
	// 权限值
    Permission interface{} `json:"permission"`
}

// RbacPermissionsPageDto 查询请求（分页） DTO
type RbacPermissionsPageDto struct {
	query.Page
	RbacPermissionsQueryDto
}

