/**
* @author long.qian
*/

package auth_rbac

// =================================================================================
// Code generated by LazyFrame Gen tool. DO NOT EDIT.
// If you want to develop the code, write the file [ gen_vo_rbac_log.go]  in the same directory.
// =================================================================================

import (
	"go-lazy-frame/pkg/pub/query"
	"go-lazy-frame/pkg/pub/util"
)

type RbacLogVo struct {
	// Id
    Id uint `json:"id"`
	// CreatedAt
    CreatedAt string `json:"createdAt"`
	// UpdatedAt
    UpdatedAt string `json:"updatedAt"`
	// DeletedAt
    DeletedAt string `json:"deletedAt"`
	// 请求Body体参数
    Body string `json:"body"`
	// IP地址
    Ip string `json:"ip"`
	// 访问地址
    Url string `json:"url"`
	// 地址参数
    UrlParams string `json:"urlParams"`
	// 登陆用户
    LoginName string `json:"loginName"`
	// 状态 0：正常 1：鉴权失败
    Status int64 `json:"status"`
}

// Transform 从实体 RbacLog 转换为 Vo
func (RbacLogVo) Transform(m RbacLog) RbacLogVo {
	vo := RbacLogVo{}
	vo.Id = m.ID
	vo.CreatedAt = util.TimeUtil.GetTimeFormatByFormat(m.CreatedAt, util.GolangBirthTime)
	vo.UpdatedAt = util.TimeUtil.GetTimeFormatByFormat(m.UpdatedAt, util.GolangBirthTime)
	vo.Body = m.Body
	vo.Ip = m.Ip
	vo.Url = m.Url
	vo.UrlParams = m.UrlParams
	vo.LoginName = m.LoginName
	vo.Status = m.Status
	return vo
}

// TransformTo 从 RbacLogVo 转换为 实体
func (me RbacLogVo) TransformTo() RbacLog {
	model := RbacLog{}
	model.ID = me.Id
	model.CreatedAt = *util.TimeUtil.TimeParseByFormat(me.CreatedAt, util.GolangBirthTime)
	model.UpdatedAt = *util.TimeUtil.TimeParseByFormat(me.UpdatedAt, util.GolangBirthTime)
	model.Body = me.Body
	model.Ip = me.Ip
	model.Url = me.Url
	model.UrlParams = me.UrlParams
	model.LoginName = me.LoginName
	model.Status = me.Status
	return model
}

type RbacLogPageVo struct {
	query.Page
	Result []RbacLogVo
}
