/**
* @author long.qian
*/

package auth_rbac

// =================================================================================
// Code generated by LazyFrame Gen tool. DO NOT EDIT.
// If you want to develop the code, write the file [ gen_model_rbac_permissions.go]  in the same directory.
// =================================================================================

import (
	"gorm.io/gorm"
)

// RbacPermissions Auth-权限
type RbacPermissions struct {
	gorm.Model
	Roles       []*RbacRole `gorm:"many2many:rbac_role_permissions"`
	Description string      `json:"description" gorm:"not null;default'';comment:权限描述"` // 权限描述
	Permission  string      `json:"permission" gorm:"unique;not null;comment:权限值"`             // 权限值
}

func (RbacPermissions) TableName() string {
	return "rbac_permissions"
}
