/**
* @author long.qian
*/

package auth_rbac

// =================================================================================
// Code generated by LazyFrame Gen tool. DO NOT EDIT.
// If you want to develop the code, write the file [ gen_model_rbac_role.go]  in the same directory.
// =================================================================================

import (
	"gorm.io/gorm"
)

// RbacRole Auth-角色
type RbacRole struct {
	gorm.Model
	Permissions []*RbacPermissions `gorm:"many2many:rbac_role_permissions"`
	Users       []*RbacUser        `gorm:"many2many:rbac_user_role"`
	RoleName    string             `json:"role_name" gorm:"unique;not null;comment:角色名"` // 角色名
	RoleDesc    string             `json:"role_desc" gorm:"not null;default:'';comment:角色描述"`           // 角色描述
	Valid       bool               `json:"valid" gorm:"type:bool;not null;default:true;comment:是否可用"`   // 是否可用
}

func (RbacRole) TableName() string {
	return "rbac_role"
}
