/**
* @author long.qian
*/

package auth_rbac

// =================================================================================
// Code generated by LazyFrame Gen tool. DO NOT EDIT.
// If you want to develop the code, write the file [ gen_model_rbac_token.go]  in the same directory.
// =================================================================================

import (
	"gorm.io/gorm"
)

// RbacToken Auth-Token
type RbacToken struct {
	gorm.Model
	Token  string `json:"token" gorm:"unique;not null;comment:Token"`               // Token
	UserId uint   `json:"user_id" gorm:"index:index_user_id;not null;comment:用户ID"` // 用户ID
}

func (RbacToken) TableName() string {
	return "rbac_token"
}
