/**
* @author long.qian
 */

package auth_rbac

// =================================================================================
// Code generated by LazyFrame Gen tool. DO NOT EDIT.
// If you want to develop the code, write the file [ gen_model_rbac_user.go]  in the same directory.
// =================================================================================

import (
	"gorm.io/gorm"
)

// RbacUser Auth-用户
type RbacUser struct {
	gorm.Model
	Roles      []*RbacRole `gorm:"many2many:rbac_user_role"`
	SuperAdmin bool        `json:"super_admin" gorm:"type:bool;not null;default:false;comment:是否超级管理员"`        // 是否超级管理员
	Admin      bool        `json:"admin" gorm:"type:bool;not null;default:false;comment:是否管理员"`                // 是否管理员
	Nickname   string      `json:"nickname" gorm:"not null;default:'';comment:昵称"`                             // 昵称
	Phone      string      `json:"phone" gorm:"not null;default:'';comment:手机号"`                               // 手机号
	LoginName  string      `json:"login_name" gorm:"unique;not null;comment:登录名"`                              //登录名
	LoginPswd  string      `json:"login_pswd" gorm:"not null;comment:登陆密码"`                                    // 登陆密码
	Salt       string      `json:"salt" gorm:"not null;comment:密码加盐"`                                          // 密码加盐
	Status     int64         `json:"status" gorm:"type:int;not null;default:1;comment:状态 1:账号正常 0:账号禁用 -1:账号违规"` // 状态 1:账号正常 0:账号禁用 -1:账号违规
}

func (RbacUser) TableName() string {
	return "rbac_user"
}
